FROM openjdk:12
RUN adduser -d /app cool-uris
ADD https://github.com/nvdk/cool-uris/releases/download/v1.0.0/cool-uris-1.0.0.jar /app/cool-uris.jar
RUN chown cool-uris:cool-uris /app/cool-uris.jar
USER cool-uris
WORKDIR /app
CMD ["java","-jar","cool-uris.jar"]